server:
  port: '8080'

spring:
  profiles:
    active: local
  application:
    name: data-gateway

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:15432/dataprovider
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest
